LibraryFinalProject/Controllers/BookController.cs
using LibraryFinalProject.IRepository;
using LibraryFinalProject.Models;
using LibraryFinalProject.Models.DbContext;
using LibraryFinalProject.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryFinalProject.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        IBookRepo BookRepository;

        public BookController(IBookRepo BookRepo)
        {
            BookRepository = BookRepo;
        }

        public IActionResult Index(string search)
        {
            List<BookAndGenreViewModel> BookList;
            if (string.IsNullOrEmpty(search))
            {
                BookList = BookRepository.AllBookAndGenre(); 
            }
            else
            {
                BookList = BookRepository.SearchBooks(search);
                ViewData["SearchQuery"] = search;
            }
            return View(BookList);
        }

        [Authorize(Roles = "Admin,Librarian")]
        public IActionResult IndexForManagers(string search)
        {
            List<BookAndGenreViewModel> BookList;
            if (string.IsNullOrEmpty(search))
            {
                BookList = BookRepository.AllBookAndGenre();
            }
            else
            {
                BookList = BookRepository.SearchBooks(search); 
                ViewData["SearchQuery"] = search;
            }
            return View(BookList);
        }

        public IActionResult Details(int id)
        {
            BookAndGenreViewModel BookViewModel = BookRepository.GetBookAndGenre(id);
            return View(BookViewModel);
        }

        [Authorize(Roles = "Admin,Librarian")]
        [HttpGet]
        public IActionResult AddBook()
        {
            BookAndGenreViewModel bookViewModel = new BookAndGenreViewModel();
            bookViewModel.genres = BookRepository.GetAllGenre();
            return View(bookViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddBook(BookAndGenreViewModel NewBookVM)
        {
            if (ModelState.IsValid)
            {
                BookRepository.Insert(NewBookVM);
                return RedirectToAction("IndexForManagers");
            }
            NewBookVM.genres = BookRepository.GetAllGenre();
            return View(NewBookVM);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Librarian")]
        public IActionResult EditBook(int id)
        {
            if (id == 0)
                return Content("Error Insert id");
            BookAndGenreViewModel BookViewModel = new BookAndGenreViewModel();
            Book Book = BookRepository.GetById(id);
            BookViewModel.Id = Book.Id;
            BookViewModel.Author = Book.Author;
            BookViewModel.Description = Book.Description;
            BookViewModel.ISBN = Book.ISBN;
            BookViewModel.Book_Photo = Book.Book_Photo;
            BookViewModel.Publish_Date = Book.Publish_Date;
            BookViewModel.Availability_Status = Book.Availability_Status;
            BookViewModel.Genre_Id = Book.Genre_Id;
            BookViewModel.Title = Book.Title;
            BookViewModel.PricePerWeek = Book.PricePerWeek;
            BookViewModel.genres = BookRepository.GetAllGenre();
            return View(BookViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditBook(int id, BookAndGenreViewModel BookVM)
        {
            if (ModelState.IsValid)
            {
                BookRepository.Update(id, BookVM);
                return RedirectToAction("IndexForManagers");
            }
            BookVM.genres = BookRepository.GetAllGenre();
            return View(BookVM);
        }

        public IActionResult DeleteBook(int id)
        {
            BookRepository.Delete(id);
            return RedirectToAction("IndexForManagers");
        }
    }
}

LibraryFinalProject/Controllers/MemberController.cs
using LibraryFinalProject.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace LibraryFinalProject.Controllers
{
    public class MemberController : Controller
    {
        IMemberRepo memberRepo;
        public MemberController(IMemberRepo memberRepo)
        {
            this.memberRepo = memberRepo;
        }
        public IActionResult Details(int id)
        {
            return View();
        }

        [Authorize]
        public IActionResult MyHistory()
        {
          
                string username = User.Identity.Name;
               

             var result =   memberRepo.historyBookViewModels(username);
                return View(result);
 

           
        }
    }
}

LibraryFinalProject/Controllers/ReturnController.cs
using LibraryFinalProject.IRepository;
using LibraryFinalProject.Models;
using LibraryFinalProject.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryFinalProject.Controllers
{
    [Authorize(Roles = "Librarian")]
    public class ReturnController : Controller
    {
        IReturnRepo ReturnRepository;
        IBookRepo BookRepository;
        IMemberRepo MemberRepository;
        ICheckoutsRepo CheckoutsRepository;
        IPenaltyRepo PenaltyRepository;
        public ReturnController(IReturnRepo returnRepo, IBookRepo bookRepo, IMemberRepo memberRepo, ICheckoutsRepo checkoutsRepo, IPenaltyRepo penaltyRepo)
        {
            ReturnRepository = returnRepo;
            BookRepository = bookRepo;
            MemberRepository = memberRepo;
            CheckoutsRepository = checkoutsRepo;
            PenaltyRepository = penaltyRepo;
        }
        public IActionResult Index()
        {
            List<ReturnViewModel> model = ReturnRepository.GetAllReturns();
            return View(model);
        }
        [HttpGet]
        public IActionResult AddReturn()
        {
            ReturnViewModel ReturnVM = new ReturnViewModel();

            var notAvailableBooks = BookRepository.GetNotAvailableBooks();
            if (notAvailableBooks == null || !notAvailableBooks.Any())
            {
                return View("ErrorInAdding");
            }

            var members = MemberRepository.GetAll();
            if (members == null || !members.Any())
            {
                return View("ErrorInAdding");
            }

            ReturnVM.NotAvailableBooks = notAvailableBooks;
            ReturnVM.Members = members;
            return View(ReturnVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddReturn(ReturnViewModel ReturnVM)
        {
            if (ModelState.IsValid)
            {
                Return Return = new Return();
                Book book = BookRepository.GetById(ReturnVM.BookId);
                if (book == null)
                {
                    ModelState.AddModelError("", "Book not found.");
                    return View(ReturnVM);
                }
                book.Availability_Status = "Available";
                BookRepository.Save();

                List<Checkouts> checkoutsList = CheckoutsRepository.GetListByBookId(ReturnVM.BookId);
                if (checkoutsList == null || !checkoutsList.Any())
                {
                    ModelState.AddModelError("", "Checkout records not found.");
                    return View(ReturnVM);
                }
                foreach (var checkouts in checkoutsList)
                {
                    var returnRecord = ReturnRepository.GetByCheckoutsId(checkouts.Id);
                    if (returnRecord == null)
                    {
                        Return.Return_Date = ReturnVM.Return_Date;
                        Return.Checkouts_Id = checkouts.Id;
                        ReturnRepository.Insert(Return);
                    }
                }
                Penalty penalty = PenaltyRepository.GetByCheckoutsId(Return.Checkouts_Id);
                return RedirectToAction("Details", "Penalty" , penalty);
            }

            return View(ReturnVM);
        }


    }
}

LibraryFinalProject/Controllers/RoleController.cs
using LibraryFinalProject.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LibraryFinalProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> RoleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.RoleManager = roleManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> New(RoleViewModel RoleVM)
        {

            if (ModelState.IsValid)
            {
                IdentityRole roleModel = new IdentityRole();
                roleModel.Name = RoleVM.RoleName;
                IdentityResult result = await RoleManager.CreateAsync(roleModel);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }
            return View(RoleVM);
        }
    }
}

LibraryFinalProject/Views/Shared/SearchPartial.cshtml
@model List<BookAndGenreViewModel>
<form method="get" asp-action="Index" class="form-inline mb-4">
    <div class="form-group">
        <label for="search" class="mr-2">Search</label>
        <input type="text" id="search" name="search" class="form-control" placeholder="Title, Author, or Genre" value="@ViewData["SearchQuery"]" />
    </div>
    <button type="submit" class="btn btn-primary ml-2">Search</button>
</form>

LibraryFinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryFinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryFinalProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item"><a class="nav-link text-dark" src="#"><h3>Kotaib</h3></a></li>
                        @if (User.IsInRole("Admin") || User.IsInRole("Librarian"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="IndexForManagers">Home Managers</a>
                            </li>
                        }
                        @if (User.IsInRole("Librarian"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Checkouts" asp-action="Index">Checkouts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Return" asp-action="Index">Returns</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Penalty" asp-action="Index">Penalties</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole("Librarian") == false && User.IsInRole("Admin") == false && User.Identity.IsAuthenticated == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="MyHistory">My History</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Penalty" asp-action="IndexForMembers" asp-route-user="@User.Identity.Name">My Penalties</a>
                            </li>
                        }


                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="AddLibrarian">Add Librarian</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="AddAdmin">Add Admin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Role" asp-action="New">Add Role</a>
                            </li>
                        }
                    </ul>
                    <ul class="nav navbar">
                        @if (User.Identity.IsAuthenticated == false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login"><h5>Login</h5></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register"><h5>Register</h5></a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout"><h5>Logout</h5></a>
                            </li>
                            <li class="nav-item">
                                <h5><a class="nav-link text-dark" asp-action="Details" asp-controller="Account" asp-route-user="@User.Identity.Name">Welcome @User.Identity.Name</a></h5>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="color:whitesmoke">
            &copy; 2024 - LibraryFinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color:whitesmoke">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</body>
</html>

<style>
    /* تأثير الأنيميشن لأزرار التنقل */
    .nav-item a {
        font-size: 1.1rem;
        font-weight: 500;
        color: #343a40; /* اللون الأساسي */
        transition: transform 0.3s ease, color 0.3s ease, background-color 0.3s ease;
        padding: 8px 20px; /* زيادة الحشو لجعل الزر أكبر */
        border-radius: 25px; /* إضافة الحواف الدائرية */
    }

        /* تأثير عند المرور على الروابط */
        .nav-item a:hover {
            transform: scale(1.1); /* تكبير الأزرار قليلاً */
            color: #fff; /* تغيير اللون إلى الأبيض */
            background-color: #007bff; /* تغيير الخلفية إلى الأزرق */
        }

    /* إضافة تأثيرات للـ Navbar */
    .navbar {
        transition: background-color 0.3s ease, box-shadow 0.3s ease;
    }

        /* إضافة تأثير شادو عند التمرير فوق Navbar */
        .navbar:hover {
            background-color: #f8f9fa;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

    /* تأثير عند الضغط على الأزرار */
    .nav-item a:active {
        transform: scale(0.95); /* تصغير الأزرار قليلاً عند الضغط */
    }

    /* تأثير الأنيميشن للـ Navbar التفاعلي */
    .navbar-toggler {
        transition: transform 0.3s ease;
    }

    .navbar-toggler-icon {
        transition: background-color 0.3s ease;
    }

    .navbar-toggler:hover .navbar-toggler-icon {
        background-color: #007bff; /* تغيير اللون عند المرور */
    }

    /* تحريك الـ NavBar بشكل جميل عند التمرير */
    .navbar-nav {
        animation: slideIn 0.5s ease-in-out;
    }

    @@keyframes slideIn {
        from {
            opacity: 0;
            transform: translateX(30px);
        }

        to {
            opacity: 1;
            transform: translateX(0);
        }
    }

    /* لتأثير الأزرار المتنقلة على الشريط العلوي عند الفتح */
    .navbar-collapse {
        transition: transform 0.3s ease-in-out;
    }

        .navbar-collapse.collapsing {
            transform: scale(0.9);
        }

        .navbar-collapse.collapse {
            transform: scale(1);
        }
</style>